## **Determinan Matriks**
Determinan adalah suatu nilai skalar yang dapat dihitung dari elemen-elemen suatu matriks persegi (matriks dengan jumlah baris dan kolom yang sama). Determinan sering digunakan dalam berbagai aplikasi, seperti menemukan invers matriks, menyelesaikan sistem persamaan linear, dan analisis transformasi linier.

Contoh Determinan Matriks Ordo 2×2

Jika diberikan matriks:

$$A=\begin{bmatrix}a&b\\c&d\end{bmatrix}$$

Maka determinannya dihitung dengan rumus:

$$\det(A)=(a\times d)-(b\times c)$$

Contoh:

$$A=\begin{bmatrix}2&3\\1&4\end{bmatrix}$$

$$\det(A)=(2\times4)-(3\times1)=8-3=5$$

**Sifat-Sifat Determinan Matriks**

1. Determinannya 1 untuk Matriks Identitas

$$\det(I_{\mathrm{n}})=1$$
2. Jika Ada Baris$f$Kolom Nol, Determinan=0
$$A=\begin{bmatrix}\mathbf1&2\\\mathbf0&\mathbf0\end{bmatrix},\quad\det(A)=0$$
3. Jika Dua Baris/Kolom Sama atau Proporsional, Determinan=0
4. Jika BarisfKolom Dikalikan $k$,Determinan Juga Dikalikan K
$$\det(A')=k\times\det(A)$$
5. Tukar Dua BarisfKolom, Determinan Berubah Tanda
$$\det(A')=-\det(A)$$
6. Matriks Segitiga: Determinan=Perkalian Diagonal
$$\det(A)=a_{11}\times a_{22}\times\cdots\times a_{\mathrm{nn}}$$

7. Determinannya Hasil Perkalian
$$\det(A\times B)=\det(A)\times\det(B)$$
8. Determinannya Invers

$$\det(A^{-1})=\frac{1}{\det(A)}$$

9. Determinannya Transpos Sama
$$\det(A^{T})=\det(A)$$

### Minor Matriks
Minor dari suatu elemen dalam matriks adalah determinan dari submatriks yang diperoleh dengan menghapus baris dan kolom yang memuat elemen tersebut.

Contoh Minor Matriks

Diberikan matriks:

$$A=\begin{bmatrix}1&2&3\\4&5&6\\7&8&9\end{bmatrix}$$

Minor dari elemen $\alpha_{11}=1$ adalah determinan dari submatriks yang diperoleh dengan menghapus baris

pertama dan kolom pertama:

$$M_{11}=\begin{bmatrix}5&6\\8&9\end{bmatrix}$$

$$\det(M_{11})=(5\times9)-(6\times8)=45-48=-3$$

## 3. Kofaktor Matriks

Kofaktor dari elemen $a_{ij}$ dalam suatu matriks adalah minor dari elemen tersebut yang dikalikan dengan
faktor tanda(-1) berpangkat $i+j:$

$$C_{ij}=(-1)^{i+j}M_{ij}$$

### Contoh Kofaktor

Dari contoh sebelumnya, kofaktor elemen $a_{11}$ adalah:

$$C_{11}=(-1)^{1+1}\times(-3)=1\times(-3)=-3$$

Sebagai contoh lain, kofaktor untuk elemen $a_{12}=2$ adalah:

$$M_{12}=\begin{bmatrix}4&6\\7&9\end{bmatrix}$$

$$\det(M_{12})=(4\times9)-(6\times7)=36-42=-6$$

$$C_{12}=(-1)^{1+2}\times(-6)=(-1)^3\times(-6)=-(-6)=6$$


Minor dan kofaktor memiliki peran penting dalam menghitung determinan matriks, terutama untuk matriks

berordo lebih dari $2\times2.$

$\bullet$ Minor dari elemen $\alpha_{ij}$ adalah determinan submatriks yang diperoleh dengan menghapus baris ke-$i$

dan kolom ke-j.

$\bullet$ Kofaktor dari elemen $a_{ij}$ adalah minor yang dikalikan dengan faktor tanda $(-1)^{i+j}.$

Hubungan dengan Determinan:

Determinan matriks dapat dihitung menggunakan perkalian baris/kolom dengan kofaktornya yang dikenal

sebagai ekspansi kofaktor

$$\det(A)=a_{i1}C_{i1}+a_{i2}C_{i2}+\cdots+a_{in}C_{in}$$

Ekspansi ini bisa dilakukan pada baris atau kolom mana saja.
Contoh untuk Matriks 3:


$$A=\begin{bmatrix}1&2&3\\4&5&6\\7&8&9\end{bmatrix}$$

Menggunakan baris pertama:

$$\det(A)=1C_{11}+2C_{12}+3C_{13}$$

Jadi, minor dan kofaktor adalah komponen utama dalam perhitungan determinan, terutama untuk matriks berukuran lebih besar

In [1]:
import numpy as np

def determinant(matrix):
    return round(np.linalg.det(matrix))

def minor(matrix, i, j):
    minor_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return determinant(minor_matrix)

def cofactor(matrix):
    size = len(matrix)
    cof_matrix = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            cof_matrix[i][j] = (-1) ** (i + j) * minor(matrix, i, j)
    return cof_matrix

# Contoh penggunaan
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Determinan:", determinant(matrix))
print("Minor (elemen [0,0]):", minor(matrix, 0, 0))
print("Matriks Kofaktor:")
print(cofactor(matrix))

Determinan: 0
Minor (elemen [0,0]): -3
Matriks Kofaktor:
[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]


**Metode Sarrus untuk Matriks 3×3**
Metode Sarrus hanya berlaku untuk matriks 3×3 dan menggunakan pola perkalian diagonal:

Diberikan matriks:
$$
A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}
$$

Langkah-langkah metode Sarrus:
1. Salin dua kolom pertama di sebelah kanan matriks:
$$
\begin{array}{ccc|cc}
a_{11} & a_{12} & a_{13} & a_{11} & a_{12} \\
a_{21} & a_{22} & a_{23} & a_{21} & a_{22} \\
a_{31} & a_{32} & a_{33} & a_{31} & a_{32} \\
\end{array}
$$
2. Hitung jumlah perkalian diagonal utama (dari kiri atas ke kanan bawah):
$$
P = (a_{11} a_{22} a_{33}) + (a_{12} a_{23} a_{31}) + (a_{13} a_{21} a_{32})
$$
3. Hitung jumlah perkalian diagonal minor (dari kanan atas ke kiri bawah):
$$
Q = (a_{13} a_{22} a_{31}) + (a_{11} a_{23} a_{32}) + (a_{12} a_{21} a_{33})
$$
4. Determinan matriks adalah:
$$
\det(A) = P - Q
$$

Contoh perhitungan dengan matriks:
$$
A = \begin{bmatrix} 2 & 3 & 1 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
$$

Hitung:
$$
P = (2 \times 5 \times 9) + (3 \times 6 \times 7) + (1 \times 4 \times 8) = 90 + 126 + 32 = 248
$$
$$
Q = (1 \times 5 \times 7) + (2 \times 6 \times 8) + (3 \times 4 \times 9) = 35 + 96 + 108 = 239
$$
$$
\det(A) = P - Q = 248 - 239 = 9
$$

### **Mencari Determinan dengan Konsep Minor dan Kofaktor**

Untuk menghitung determinan menggunakan konsep minor dan kofaktor, kita menggunakan ekspansi

kofaktor, yaitu:

$$\det(A)=a_{i1}C_{i1}+a_{i2}C_{i2}+\cdots+a_{in}C_{in}$$

di mana:

$\cdot$ $C_{ij}$ adalah kofaktor elemen $a_ij$, dihitung sebagai:

$$C_{ij}=(-1)^{i+j}M_{ij}$$

$\cdot$ $M_{ij}$ adalah minor, yaitu determinan submatriks yang diperoleh dengan menghapus baris ke- $i$ dan kolom ke-$j$.

**Contoh Perhitungan**

**1. Determinan Matriks 3×3**
Diberikan matriks:
$$
A = \begin{bmatrix} 2 & 3 & 1 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}
$$

Gunakan ekspansi baris pertama:
$$
\det(A) = 2C_{11} + 3C_{12} + 1C_{13}
$$

Hitung minor dan kofaktor:
$$
M_{11} = \begin{bmatrix} 5 & 6 \\ 8 & 9 \end{bmatrix}, \quad \det(M_{11}) = (5 \times 9) - (6 \times 8) = -3
$$
$$
C_{11} = (-1)^{1+1} (-3) = -3
$$

$$
M_{12} = \begin{bmatrix} 4 & 6 \\ 7 & 9 \end{bmatrix}, \quad \det(M_{12}) = (4 \times 9) - (6 \times 7) = -6
$$
$$
C_{12} = (-1)^{1+2} (-6) = 6
$$

$$
M_{13} = \begin{bmatrix} 4 & 5 \\ 7 & 8 \end{bmatrix}, \quad \det(M_{13}) = (4 \times 8) - (5 \times 7) = -3
$$
$$
C_{13} = (-1)^{1+3} (-3) = -3
$$

$$
\det(A) = (2 \times -3) + (3 \times 6) + (1 \times -3) = -6 + 18 - 3 = 9
$$


**2. Determinan Matriks 4×4**
Diberikan matriks:
$$
B = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 2 & 3 & 4 & 5 \\ 3 & 4 & 5 & 6 \\ 4 & 5 & 6 & 7 \end{bmatrix}
$$

Gunakan ekspansi baris pertama:
$$
\det(B) = 1C_{11} - 2C_{12} + 3C_{13} - 4C_{14}
$$
Hitung masing-masing minor dan kofaktor, lalu gunakan determinan 3×3 seperti pada contoh sebelumnya.

**3. Determinan Matriks 5×5**
Diberikan matriks:
$$
C = \begin{bmatrix} 1 & 2 & 3 & 4 & 5 \\ 2 & 3 & 4 & 5 & 6 \\ 3 & 4 & 5 & 6 & 7 \\ 4 & 5 & 6 & 7 & 8 \\ 5 & 6 & 7 & 8 & 9 \end{bmatrix}
$$

Gunakan ekspansi baris pertama dan ulangi proses perhitungan determinan 4×4.
